### ISSUE TITLE
[SP: 10] As a user, I would like to let the application dictate my current Wikipedia article.

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#13]
- [x] Implement a dictation button using the Google API to dictate all the text content in the current article. SP: 2 #19
- [x] Wiki app text access function need to be stored in to strings. SP: 3 #22
- [x] Text to speech implementation able to read the strings out loud. SP: 3 #23 
- [x] Implement the necessary testings (UI and Unit Testings) for the added features. SP: 2 #20

Story points: 10
