### ISSUE TITLE
[SP: 10] As a user, I would like to be notified regularly to read a random article on the Wikipedia app.

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#14]
- [x] Implement a notification popup at a specified time period (e.g. one everyday at 12pm). SP: 5 #20
- [x] Link the notification to a random article using the random article feature already implemented within the application. SP: 3 #17
- [x] Implement the necessary testings (UI and Unit Testings) for the added features. SP: 2  #18

SP: 10
