### ISSUE TITLE
[SP: 20] As a user, I would like to generate a citation(MLA, APA, IEEE in String or LaTeX) for my current Wikipedia article on the mobile application.

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#27]
- [x] Implement a citation button on the bottom on the article action navigation bar. SP: 3 #28
- [x] Return an activity with the MLA/APA/IEEE String. SP: 8 #29
- [x] Add a copy button next to the MLA/APA/IEEE/LaTeX String. SP: 3 #30
- [x] Implement the proper testings for the citation generator Feature. SP: 6 #31

SP: 20
