### ISSUE TITLE
[SP: 6]As a developper, I would like to have my GitHub repository be setup and be compatible with CircleCI and Espresso UI Test

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#3]
- [x] Setup the GitHub repository so developers can formally use. SP: 2 #8 
- [x] Setup CircleCI. SP: 2 #1 
- [x] Setup Espresso UI Testing. SP: 2 #9 

Story Points: 6
