### ISSUE TITLE
As a user, I would like to generate a QR code URL that points to the current Wikipedia application article. SP: 10

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#33]
Related to #32 

- [x] Implement a button in the share article menu to show a popup to insert the QR code. SP: 4 #34 
- [x] Generate the QR code of the current article and insert it on the activity page. SP: 4 #35 
- [x] Implement the proper testing for the QR code generator in the share article menu. SP: 2 #36 

SP: 10
