### ISSUE TITLE
[SP: 15]As a user, I want a functional QR code reader within the application to scan the URLs for other Wikipedia articles.

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#37]
Related to #32 

- [x] Implement a quick access menu option on the left navigation menu that triggers the QR code scanner. SP: 4 #38 
- [x] Implement the QR code scanner API to scan generic URLs. SP: 5 #39 
- [x] Implement a restriction where the user can only scan Wikipedia application articles. SP: 3 #40 
- [x] Implement the proper testing for QR code reader. SP: 3 #41
