### ISSUE TITLE
[SP: 15] As a user, I would want to take a picture so that Wikipedia will suggest me articles related to objects in the picture.

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#61]
- [x] Implement a third-party login from a social media by using Firestore. SP: 4 #64 
- [x] Move the Scan QR Code camera to the login platform. SP: 2 #65
- [x] Make a the camera button being able to take a picture and process it through FireStore - Google Cloud Image Processing API. SP: 5 #66 
- [x] Using the Image Processing API, implement an article suggestion page by using the keywords from the API's keywords.  SP: 4 #67

* Also implement the proper testings for each method/UI
