### ISSUE TITLE
[SP: 20]As a user, I want to share my article or my note by using NFC on my device to another nearby user.

### ISSUE THREAD

**Issue by AznBoy00** [AznBoy00/SOEN390TeamFandroidsWiki#94]
- [x] Broadcast Article NFC Signal + Testing SP: 5
- [x] Receiving Article NFC Signal + Testing SP: 5
- [x] Broadcast Note via NFC Signal + Testing SP: 5
- [x] Receiving Note via NFC Signal + Testing SP: 5
